/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import modelo.IUserDAO;
import modelo.User;
import modelo.UserDaoImpl;
import vista.ResultSetTableModel;

/**
 *
 * @author Chente
 */
public class FrameUsers extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrameUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jplIngreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbConsultas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tl = new javax.swing.JLabel();
        txtpayment_id = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        labelpf = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnrestablecer = new javax.swing.JButton();
        rbAltas1 = new javax.swing.JRadioButton();
        rbBajas = new javax.swing.JRadioButton();
        rbCambios = new javax.swing.JRadioButton();
        txtpassword = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtfirst_name = new javax.swing.JTextField();
        txtlast_name = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        txtperformance_factor = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtuser_id = new javax.swing.JTextField();
        lblc = new javax.swing.JLabel();
        txtcellphone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ScrollPaneTablaUsers = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();
        btnValidar = new javax.swing.JButton();

        bg.add(rbAltas1);
        bg.add(rbBajas);
        bg.add(rbCambios);
        bg.add(rbConsultas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplIngreso.setBackground(new java.awt.Color(204, 204, 0));
        jplIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplIngreso.setForeground(new java.awt.Color(204, 204, 0));
        jplIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario-hombre.png"))); // NOI18N
        jplIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 110));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Opciones");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jplIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rbConsultas.setBackground(new java.awt.Color(51, 51, 51));
        rbConsultas.setForeground(new java.awt.Color(255, 255, 255));
        rbConsultas.setText("Consultas");
        rbConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbConsultasActionPerformed(evt);
            }
        });
        jplIngreso.add(rbConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("email@:");
        jplIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 20));
        jplIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, 10));

        tl.setForeground(new java.awt.Color(0, 0, 0));
        tl.setText("payment_id");
        jplIngreso.add(tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, 20));

        txtpayment_id.setBackground(new java.awt.Color(51, 51, 51));
        txtpayment_id.setForeground(new java.awt.Color(255, 255, 255));
        txtpayment_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayment_idActionPerformed(evt);
            }
        });
        txtpayment_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpayment_idKeyTyped(evt);
            }
        });
        jplIngreso.add(txtpayment_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 120, 20));
        jplIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 10));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("password:");
        jplIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 20));
        jplIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 270, 10));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("first_name:");
        jplIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, 20));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("last_name:");
        jplIngreso.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 20));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("adress:");
        jplIngreso.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, 20));

        labelpf.setForeground(new java.awt.Color(0, 0, 0));
        labelpf.setText("Performance_Factor:");
        jplIngreso.add(labelpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, 20));
        jplIngreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 10));
        jplIngreso.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 270, 10));
        jplIngreso.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, 10));
        jplIngreso.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 10));

        btnrestablecer.setBackground(new java.awt.Color(51, 51, 51));
        btnrestablecer.setForeground(new java.awt.Color(51, 51, 51));
        btnrestablecer.setText("Restablecer");
        btnrestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrestablecerMouseClicked(evt);
            }
        });
        btnrestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestablecerActionPerformed(evt);
            }
        });
        btnrestablecer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnrestablecerKeyPressed(evt);
            }
        });
        jplIngreso.add(btnrestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 542, 100, 30));

        rbAltas1.setBackground(new java.awt.Color(51, 51, 51));
        rbAltas1.setForeground(new java.awt.Color(255, 255, 255));
        rbAltas1.setText("Altas");
        rbAltas1.setSelected(true);
        rbAltas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAltas1MouseClicked(evt);
            }
        });
        rbAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAltas1ActionPerformed(evt);
            }
        });
        jplIngreso.add(rbAltas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        rbBajas.setBackground(new java.awt.Color(51, 51, 51));
        rbBajas.setForeground(new java.awt.Color(255, 255, 255));
        rbBajas.setText("Bajas");
        rbBajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbBajasMouseClicked(evt);
            }
        });
        rbBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBajasActionPerformed(evt);
            }
        });
        jplIngreso.add(rbBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        rbCambios.setBackground(new java.awt.Color(51, 51, 51));
        rbCambios.setForeground(new java.awt.Color(255, 255, 255));
        rbCambios.setText("Cambios");
        rbCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCambiosMouseClicked(evt);
            }
        });
        rbCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCambiosActionPerformed(evt);
            }
        });
        jplIngreso.add(rbCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        txtpassword.setBackground(new java.awt.Color(51, 51, 51));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jplIngreso.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, 20));

        txtemail.setBackground(new java.awt.Color(51, 51, 51));
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jplIngreso.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, -1));

        txtfirst_name.setBackground(new java.awt.Color(51, 51, 51));
        txtfirst_name.setForeground(new java.awt.Color(255, 255, 255));
        txtfirst_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirst_nameActionPerformed(evt);
            }
        });
        jplIngreso.add(txtfirst_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, -1));

        txtlast_name.setBackground(new java.awt.Color(51, 51, 51));
        txtlast_name.setForeground(new java.awt.Color(255, 255, 255));
        txtlast_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlast_nameActionPerformed(evt);
            }
        });
        jplIngreso.add(txtlast_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, -1));

        txtadress.setBackground(new java.awt.Color(51, 51, 51));
        txtadress.setForeground(new java.awt.Color(255, 255, 255));
        txtadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadressActionPerformed(evt);
            }
        });
        jplIngreso.add(txtadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, -1));

        txtperformance_factor.setBackground(new java.awt.Color(51, 51, 51));
        txtperformance_factor.setForeground(new java.awt.Color(255, 255, 255));
        txtperformance_factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperformance_factorActionPerformed(evt);
            }
        });
        jplIngreso.add(txtperformance_factor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 394, 130, 30));

        btnagregar.setBackground(new java.awt.Color(51, 51, 51));
        btnagregar.setForeground(new java.awt.Color(51, 51, 51));
        btnagregar.setText("Agregar");
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        btnagregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnagregarKeyPressed(evt);
            }
        });
        jplIngreso.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, -1));

        btncancelar.setBackground(new java.awt.Color(51, 51, 51));
        btncancelar.setForeground(new java.awt.Color(51, 51, 51));
        btncancelar.setText("Cancelar");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jplIngreso.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 100, 30));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("user_id:");
        jplIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 20));

        txtuser_id.setBackground(new java.awt.Color(51, 51, 51));
        txtuser_id.setForeground(new java.awt.Color(255, 255, 255));
        txtuser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuser_idActionPerformed(evt);
            }
        });
        txtuser_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser_idKeyTyped(evt);
            }
        });
        jplIngreso.add(txtuser_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 220, -1));

        lblc.setForeground(new java.awt.Color(0, 0, 0));
        lblc.setText("cellphone:");
        jplIngreso.add(lblc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 60, 20));

        txtcellphone.setBackground(new java.awt.Color(51, 51, 51));
        txtcellphone.setForeground(new java.awt.Color(255, 255, 255));
        txtcellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcellphoneActionPerformed(evt);
            }
        });
        jplIngreso.add(txtcellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 130, 30));

        getContentPane().add(jplIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 0));

        btnBuscar.setText("Buscar");
        btnBuscar.setVisible(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBuscar)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaUsers.setBackground(new java.awt.Color(102, 102, 102));
        TablaUsers.setForeground(new java.awt.Color(255, 255, 255));
        TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "user_id", "password", "email@", "first_name", "last_name", "address", "performance_factor", "cellphone", "payment_id"
            }
        ));
        ScrollPaneTablaUsers.setViewportView(TablaUsers);

        jPanel1.add(ScrollPaneTablaUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 340));

        btnValidar.setVisible(false);
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbConsultasActionPerformed

    private void txtpayment_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayment_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayment_idActionPerformed

    private void btnrestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestablecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestablecerActionPerformed

    private void rbAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAltas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAltas1ActionPerformed

    private void rbBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBajasActionPerformed

    private void rbCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCambiosActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtfirst_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirst_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirst_nameActionPerformed

    private void txtlast_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlast_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlast_nameActionPerformed

    private void txtadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadressActionPerformed

    private void txtperformance_factorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperformance_factorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperformance_factorActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnagregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnagregarKeyPressed

       
    }//GEN-LAST:event_btnagregarKeyPressed

    private void txtuser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser_idActionPerformed

    private void txtcellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcellphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcellphoneActionPerformed

    private void funcionAltas(){
         if(txtuser_id.getText().equals("")){
         txtuser_id.setBackground(Color.red);
          txtuser_id.setText("Campo VACIO");
         txtuser_id.requestFocus();
     } else if(txtemail.getText().equals("")){
         txtemail.setBackground(Color.red);
         txtemail.setText("Campo VACIO");
         txtemail.requestFocus();
         
     }else if(txtpassword.getText().equals("")){
         txtpassword.setBackground(Color.red);
         txtpassword.setText("Campo VACIO");
         txtpassword.requestFocus();
     }else if(txtfirst_name.getText().equals("")){
         txtfirst_name.setBackground(Color.red);
         txtfirst_name.setText("Campo VACIO");
         txtfirst_name.requestFocus();
     }else if(txtlast_name.getText().equals("")){
         txtlast_name.setBackground(Color.red);
         txtlast_name.setText("Campo VACIO");
         txtlast_name.requestFocus();
     }else if(txtadress.getText().equals("")){
         txtadress.setBackground(Color.red);
         txtadress.setText("Campo VACIO");
         txtadress.requestFocus();
     }else if(txtperformance_factor.getText().equals("")){
         txtperformance_factor.setBackground(Color.red);
         txtperformance_factor.setText("Campo VACIO");
         txtperformance_factor.requestFocus();
     }else if(txtcellphone.getText().equals("")){
         txtcellphone.setBackground(Color.red);
         txtcellphone.setText("Campo VACIO");
         txtcellphone.requestFocus();
     }else if(txtpayment_id.getText().equals("")){
         txtpayment_id.setBackground(Color.red);
         txtpayment_id.setText("Campo VACIO");
         txtpayment_id.requestFocus();
     }else{
         
          IUserDAO dao = new UserDaoImpl();
        int user_id = Integer.parseInt(txtuser_id.getText());
        String email = txtemail.getText();
        String password = txtpassword.getText();
     String first_name = txtfirst_name.getText();
     String last_name = txtlast_name.getText();
     String address = txtadress.getText();
     String performance_factor = txtperformance_factor.getText();
    String cellphone = txtcellphone.getText();
     int payment_id = Integer.parseInt(txtpayment_id.getText());
     
     User user = new User(user_id,email,password,first_name,last_name,address
     ,performance_factor,cellphone,payment_id);
           if(dao.registrar(user)){
         btnValidar.setVisible(true);
         btnValidar.setText("Registro COMPLETADO");
         actualizarTabla();
         
     }else{
         btnValidar.setVisible(true);
         btnValidar.setText("Registro NO COMPLETADO");
     }
    }
    }
    
    public void funcionBajas(){
        UserDaoImpl dao = new UserDaoImpl();
        User usuarioRecibido = dao.obtenerusuario(txtuser_id.getText());
        if(dao.eliminar(usuarioRecibido)){
            txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtemail.setText("");
        txtemail.setBackground(Color.GRAY);
        txtpassword.setText("");
        txtpassword.setBackground(Color.GRAY);
        txtfirst_name.setText("");
        txtfirst_name.setBackground(Color.GRAY);
        txtlast_name.setText("");
        txtlast_name.setBackground(Color.GRAY);
        txtadress.setText("");
        txtadress.setBackground(Color.GRAY);
        txtperformance_factor.setText("");
        txtperformance_factor.setBackground(Color.GRAY);
        txtcellphone.setText("");
        txtcellphone.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        
        btnValidar.setVisible(true);
                 btnValidar.setText("Eliminacion exitosa");
                 actualizarTabla();
        }else{
            btnValidar.setVisible(true);
                 btnValidar.setText("Eliminacion fallida");
                 btnValidar.setBackground(Color.red);
        }
        
    }
    
    private void funcionCambios(){
         if(txtuser_id.getText().equals("")){
         txtuser_id.setBackground(Color.red);
          txtuser_id.setText("Campo VACIO");
         txtuser_id.requestFocus();
     } else if(txtemail.getText().equals("")){
         txtemail.setBackground(Color.red);
         txtemail.setText("Campo VACIO");
         txtemail.requestFocus();
         
     }else if(txtpassword.getText().equals("")){
         txtpassword.setBackground(Color.red);
         txtpassword.setText("Campo VACIO");
         txtpassword.requestFocus();
     }else if(txtfirst_name.getText().equals("")){
         txtfirst_name.setBackground(Color.red);
         txtfirst_name.setText("Campo VACIO");
         txtfirst_name.requestFocus();
     }else if(txtlast_name.getText().equals("")){
         txtlast_name.setBackground(Color.red);
         txtlast_name.setText("Campo VACIO");
         txtlast_name.requestFocus();
     }else if(txtadress.getText().equals("")){
         txtadress.setBackground(Color.red);
         txtadress.setText("Campo VACIO");
         txtadress.requestFocus();
     }else if(txtperformance_factor.getText().equals("")){
         txtperformance_factor.setBackground(Color.red);
         txtperformance_factor.setText("Campo VACIO");
         txtperformance_factor.requestFocus();
     }else if(txtcellphone.getText().equals("")){
         txtcellphone.setBackground(Color.red);
         txtcellphone.setText("Campo VACIO");
         txtcellphone.requestFocus();
     }else if(txtpayment_id.getText().equals("")){
         txtpayment_id.setBackground(Color.red);
         txtpayment_id.setText("Campo VACIO");
         txtpayment_id.requestFocus();
     }else{
         
          IUserDAO dao = new UserDaoImpl();
        int user_id = Integer.parseInt(txtuser_id.getText());
        String email = txtemail.getText();
        String password = txtpassword.getText();
     String first_name = txtfirst_name.getText();
     String last_name = txtlast_name.getText();
     String address = txtadress.getText();
     String performance_factor = txtperformance_factor.getText();
    String cellphone = txtcellphone.getText();
     int payment_id = Integer.parseInt(txtpayment_id.getText());
     
     User user = new User(user_id,email,password,first_name,last_name,address
     ,performance_factor,cellphone,payment_id);
           if(dao.actualizar(user)){
         btnValidar.setVisible(true);
         btnValidar.setText("Actualizacion COMPLETADA");
         actualizarTabla();
         
     }else{
         btnValidar.setVisible(true);
         btnValidar.setText("Actualizacion NO COMPLETADO");
     }
    }

        
}
    
    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked
        // TODO add your handling code here:
        if(rbAltas1.isSelected()){
           funcionAltas(); 
        }else if(rbBajas.isSelected()){
            funcionBajas();
        }else if(rbCambios.isSelected()){
            funcionCambios();
        }
        
     
     
     
   
     
     
    }//GEN-LAST:event_btnagregarMouseClicked

    private void txtuser_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txtuser_id.setText("Ingresa Solo Numeros");}
        
        
    }//GEN-LAST:event_txtuser_idKeyTyped

    private void txtpayment_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayment_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txtpayment_id.setText("Ingresa Solo Numeros");}
    }//GEN-LAST:event_txtpayment_idKeyTyped

    private void btnrestablecerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnrestablecerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestablecerKeyPressed

    private void btnrestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrestablecerMouseClicked
        // TODO add your handling code here:
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtemail.setText("");
        txtemail.setBackground(Color.GRAY);
        txtpassword.setText("");
        txtpassword.setBackground(Color.GRAY);
        txtfirst_name.setText("");
        txtfirst_name.setBackground(Color.GRAY);
        txtlast_name.setText("");
        txtlast_name.setBackground(Color.GRAY);
        txtadress.setText("");
        txtadress.setBackground(Color.GRAY);
        txtperformance_factor.setText("");
        txtperformance_factor.setBackground(Color.GRAY);
        txtcellphone.setText("");
        txtcellphone.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnrestablecerMouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarMouseClicked

    private void rbBajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbBajasMouseClicked
        // TODO add your handling code here:
        btnValidar.setVisible(false);
        btnBuscar.setVisible(true);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtemail.setText("");
        txtemail.setBackground(Color.GRAY);
        txtpassword.setText("");
        txtpassword.setBackground(Color.GRAY);
        txtfirst_name.setText("");
        txtfirst_name.setBackground(Color.GRAY);
        txtlast_name.setText("");
        txtlast_name.setBackground(Color.GRAY);
        txtadress.setText("");
        txtadress.setBackground(Color.GRAY);
        txtperformance_factor.setText("");
        txtperformance_factor.setBackground(Color.GRAY);
        txtcellphone.setText("");
        txtcellphone.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        btnagregar.setText("Eliminar");
        
    }//GEN-LAST:event_rbBajasMouseClicked

    private void rbAltas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAltas1MouseClicked
        // TODO add your handling code here:
         btnBuscar.setVisible(false);
         btnValidar.setVisible(false);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtemail.setText("");
        txtemail.setBackground(Color.GRAY);
        txtpassword.setText("");
        txtpassword.setBackground(Color.GRAY);
        txtfirst_name.setText("");
        txtfirst_name.setBackground(Color.GRAY);
        txtlast_name.setText("");
        txtlast_name.setBackground(Color.GRAY);
        txtadress.setText("");
        txtadress.setBackground(Color.GRAY);
        txtperformance_factor.setText("");
        txtperformance_factor.setBackground(Color.GRAY);
        txtcellphone.setText("");
        txtcellphone.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        btnagregar.setText("Agregar");
    }//GEN-LAST:event_rbAltas1MouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if(txtuser_id.getText().equals("")){
            txtuser_id.setText("Ingrese ID ....");
            txtuser_id.setBackground(Color.CYAN);
        }
        else{
            UserDaoImpl dao = new UserDaoImpl();
            User usuarioRecibido = dao.obtenerusuario(txtuser_id.getText());
            txtuser_id.setText(String.valueOf(usuarioRecibido.getUser_id()));
            txtemail.setText(usuarioRecibido.getEmail());
            txtpassword.setText(usuarioRecibido.getPassword());
            txtfirst_name.setText(usuarioRecibido.getFirst_name());
            txtlast_name.setText(usuarioRecibido.getLast_name());
            txtadress.setText(usuarioRecibido.getAddress());
            txtperformance_factor.setText(usuarioRecibido.getPerformance_factor());
            txtcellphone.setText(usuarioRecibido.getCellphone());
            txtpayment_id.setText(String.valueOf(usuarioRecibido.getPayment_id()));
            
            
  
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void armarConsulta(){
       
        
    }
    
    private void rbCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCambiosMouseClicked
        // TODO add your handling code here:
        btnValidar.setVisible(false);
        btnBuscar.setVisible(true);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtemail.setText("");
        txtemail.setBackground(Color.GRAY);
        txtpassword.setText("");
        txtpassword.setBackground(Color.GRAY);
        txtfirst_name.setText("");
        txtfirst_name.setBackground(Color.GRAY);
        txtlast_name.setText("");
        txtlast_name.setBackground(Color.GRAY);
        txtadress.setText("");
        txtadress.setBackground(Color.GRAY);
        txtperformance_factor.setText("");
        txtperformance_factor.setBackground(Color.GRAY);
        txtcellphone.setText("");
        txtcellphone.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        btnagregar.setText("Actualizar");
        
    }//GEN-LAST:event_rbCambiosMouseClicked
     
    public void actualizarTabla(){

        final String TABLA_USERS = "users";//esto pede ser parametro

        String driver = "com.ibm.db2.jcc.DB2Driver";
        String url = "jdbc:db2://localhost:50000/DB_SPS";
        String user = "chester";
        String password = "chesterf51997";
        String query = "SELECT * FROM CHENTE." + TABLA_USERS;

        ResultSetTableModel modelo = null;
        try {
            modelo = new ResultSetTableModel(driver, url, user, password, query);
        } catch (SQLException e1) {
            e1.printStackTrace();
        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        }

        TablaUsers.setModel(modelo);

    }
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneTablaUsers;
    private javax.swing.JTable TablaUsers;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnrestablecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jplIngreso;
    private javax.swing.JLabel labelpf;
    private javax.swing.JLabel lblc;
    private javax.swing.JRadioButton rbAltas1;
    private javax.swing.JRadioButton rbBajas;
    private javax.swing.JRadioButton rbCambios;
    private javax.swing.JRadioButton rbConsultas;
    private javax.swing.JLabel tl;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtcellphone;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirst_name;
    private javax.swing.JTextField txtlast_name;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtpayment_id;
    private javax.swing.JTextField txtperformance_factor;
    private javax.swing.JTextField txtuser_id;
    // End of variables declaration//GEN-END:variables
}
