/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import modelo.IUserDAO;
import modelo.IUserTransactionDAO;
import modelo.User;
import modelo.UserDaoImpl;
import modelo.UserTransaction;
import modelo.UserTransactionDaoImpl;
import vista.ResultSetTableModel;

/**
 *
 * @author Chente
 */
public class FrameUsersTransaction extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrameUsersTransaction() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jplIngreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbConsultas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnrestablecer = new javax.swing.JButton();
        rbAltas1 = new javax.swing.JRadioButton();
        rbBajas = new javax.swing.JRadioButton();
        rbCambios = new javax.swing.JRadioButton();
        txtuser_id = new javax.swing.JTextField();
        txtpayment_id = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txttransaction_id = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtcomment = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        cbtransaction_id = new javax.swing.JCheckBox();
        cbuser_id = new javax.swing.JCheckBox();
        cbpayment_id = new javax.swing.JCheckBox();
        cbamount = new javax.swing.JCheckBox();
        cbcomment = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        ScrollPaneTablaUsers = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();
        btnValidar = new javax.swing.JButton();
        btnVisor = new javax.swing.JButton();
        cbtransaction_id1 = new javax.swing.JCheckBox();
        cbuser_id1 = new javax.swing.JCheckBox();
        cbpayment_id1 = new javax.swing.JCheckBox();
        cbamount1 = new javax.swing.JCheckBox();
        cbcomment1 = new javax.swing.JCheckBox();
        cbtype2 = new javax.swing.JCheckBox();
        cbtype = new javax.swing.JCheckBox();

        bg.add(rbAltas1);
        bg.add(rbBajas);
        bg.add(rbCambios);
        bg.add(rbConsultas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplIngreso.setBackground(new java.awt.Color(204, 204, 0));
        jplIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplIngreso.setForeground(new java.awt.Color(204, 204, 0));
        jplIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank.png"))); // NOI18N
        jplIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 110));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Opciones");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jplIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rbConsultas.setBackground(new java.awt.Color(51, 51, 51));
        rbConsultas.setForeground(new java.awt.Color(255, 255, 255));
        rbConsultas.setText("Consultas");
        rbConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbConsultasMouseClicked(evt);
            }
        });
        rbConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbConsultasActionPerformed(evt);
            }
        });
        jplIngreso.add(rbConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("payment_id");
        jplIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 20));
        jplIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, 10));
        jplIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 10));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("user_id:");
        jplIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 20));
        jplIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 270, 10));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("amount:");
        jplIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, 20));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("type:");
        jplIngreso.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 20));
        jplIngreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 10));
        jplIngreso.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 270, 10));
        jplIngreso.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, 10));
        jplIngreso.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 10));

        btnrestablecer.setBackground(new java.awt.Color(51, 51, 51));
        btnrestablecer.setForeground(new java.awt.Color(51, 51, 51));
        btnrestablecer.setText("Restablecer");
        btnrestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrestablecerMouseClicked(evt);
            }
        });
        btnrestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestablecerActionPerformed(evt);
            }
        });
        btnrestablecer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnrestablecerKeyPressed(evt);
            }
        });
        jplIngreso.add(btnrestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 542, 100, 30));

        rbAltas1.setBackground(new java.awt.Color(51, 51, 51));
        rbAltas1.setForeground(new java.awt.Color(255, 255, 255));
        rbAltas1.setText("Altas");
        rbAltas1.setSelected(true);
        rbAltas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAltas1MouseClicked(evt);
            }
        });
        rbAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAltas1ActionPerformed(evt);
            }
        });
        jplIngreso.add(rbAltas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        rbBajas.setBackground(new java.awt.Color(51, 51, 51));
        rbBajas.setForeground(new java.awt.Color(255, 255, 255));
        rbBajas.setText("Bajas");
        rbBajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbBajasMouseClicked(evt);
            }
        });
        rbBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBajasActionPerformed(evt);
            }
        });
        jplIngreso.add(rbBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        rbCambios.setBackground(new java.awt.Color(51, 51, 51));
        rbCambios.setForeground(new java.awt.Color(255, 255, 255));
        rbCambios.setText("Cambios");
        rbCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCambiosMouseClicked(evt);
            }
        });
        rbCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCambiosActionPerformed(evt);
            }
        });
        jplIngreso.add(rbCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        txtuser_id.setBackground(new java.awt.Color(51, 51, 51));
        txtuser_id.setForeground(new java.awt.Color(255, 255, 255));
        txtuser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuser_idActionPerformed(evt);
            }
        });
        txtuser_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuser_idKeyTyped(evt);
            }
        });
        jplIngreso.add(txtuser_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, 20));

        txtpayment_id.setBackground(new java.awt.Color(51, 51, 51));
        txtpayment_id.setForeground(new java.awt.Color(255, 255, 255));
        txtpayment_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayment_idActionPerformed(evt);
            }
        });
        txtpayment_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpayment_idKeyTyped(evt);
            }
        });
        jplIngreso.add(txtpayment_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, -1));

        txtamount.setBackground(new java.awt.Color(51, 51, 51));
        txtamount.setForeground(new java.awt.Color(255, 255, 255));
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamountKeyTyped(evt);
            }
        });
        jplIngreso.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, -1));

        txttype.setBackground(new java.awt.Color(51, 51, 51));
        txttype.setForeground(new java.awt.Color(255, 255, 255));
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });
        jplIngreso.add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, -1));

        btnagregar.setBackground(new java.awt.Color(51, 51, 51));
        btnagregar.setForeground(new java.awt.Color(51, 51, 51));
        btnagregar.setText("Agregar");
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        btnagregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnagregarKeyPressed(evt);
            }
        });
        jplIngreso.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, -1));

        btncancelar.setBackground(new java.awt.Color(51, 51, 51));
        btncancelar.setForeground(new java.awt.Color(51, 51, 51));
        btncancelar.setText("Cancelar");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jplIngreso.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 100, 30));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("transaction_id:");
        jplIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        txttransaction_id.setBackground(new java.awt.Color(51, 51, 51));
        txttransaction_id.setForeground(new java.awt.Color(255, 255, 255));
        txttransaction_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttransaction_idActionPerformed(evt);
            }
        });
        txttransaction_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttransaction_idKeyTyped(evt);
            }
        });
        jplIngreso.add(txttransaction_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, -1));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("comment:");
        jplIngreso.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 20));

        txtcomment.setBackground(new java.awt.Color(51, 51, 51));
        txtcomment.setForeground(new java.awt.Color(255, 255, 255));
        txtcomment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcommentActionPerformed(evt);
            }
        });
        jplIngreso.add(txtcomment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, -1));

        getContentPane().add(jplIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 0));

        btnBuscar.setText("Buscar");
        btnBuscar.setVisible(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        cbtransaction_id.setText("transaction_id");
        cbtransaction_id.setVisible(false);

        cbuser_id.setText("user_id");
        cbuser_id.setVisible(false);
        cbuser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuser_idActionPerformed(evt);
            }
        });

        cbpayment_id.setText("payment_id");
        cbpayment_id.setVisible(false);

        cbamount.setText("amount");
        cbamount.setVisible(false);

        cbcomment.setText("comment");
        cbcomment.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbtransaction_id)
                .addGap(18, 18, 18)
                .addComponent(cbuser_id)
                .addGap(26, 26, 26)
                .addComponent(cbpayment_id)
                .addGap(33, 33, 33)
                .addComponent(cbamount)
                .addGap(35, 35, 35)
                .addComponent(cbcomment)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(cbtransaction_id)
                    .addComponent(cbuser_id)
                    .addComponent(cbpayment_id)
                    .addComponent(cbamount)
                    .addComponent(cbcomment))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaUsers.setBackground(new java.awt.Color(102, 102, 102));
        TablaUsers.setForeground(new java.awt.Color(255, 255, 255));
        TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "transaction_id", "user_id", "payment_id", "amount", "type", "comment"
            }
        ));
        ScrollPaneTablaUsers.setViewportView(TablaUsers);

        jPanel1.add(ScrollPaneTablaUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 340));

        btnValidar.setVisible(false);
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));

        btnVisor.setText("visor sql");
        btnVisor.setVisible(false);
        btnVisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisorMouseClicked(evt);
            }
        });
        jPanel1.add(btnVisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        cbtransaction_id1.setText("transaction_id");
        cbtransaction_id1.setVisible(false);
        jPanel1.add(cbtransaction_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        cbuser_id1.setText("user_id");
        cbuser_id1.setVisible(false);
        cbuser_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuser_id1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbuser_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        cbpayment_id1.setText("payment_id");
        cbpayment_id1.setVisible(false);
        jPanel1.add(cbpayment_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        cbamount1.setText("amount");
        cbamount1.setVisible(false);
        jPanel1.add(cbamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        cbcomment1.setText("comment");
        cbcomment1.setVisible(false);
        jPanel1.add(cbcomment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        cbtype2.setText("type");
        cbtype2.setVisible(false);
        jPanel1.add(cbtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        cbtype.setText("type");
        cbcomment.setVisible(false);
        cbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtypeActionPerformed(evt);
            }
        });
        cbtype.setVisible(false);
        jPanel1.add(cbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbConsultasActionPerformed

    private void btnrestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestablecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestablecerActionPerformed

    private void rbAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAltas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAltas1ActionPerformed

    private void rbBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBajasActionPerformed

    private void rbCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCambiosActionPerformed

    private void txtuser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser_idActionPerformed

    private void txtpayment_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayment_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayment_idActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnagregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnagregarKeyPressed

       
    }//GEN-LAST:event_btnagregarKeyPressed

    private void txttransaction_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttransaction_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttransaction_idActionPerformed

    private void tablaOriginal(){
        TablaUsers.setBackground(new java.awt.Color(102, 102, 102));

TablaUsers.setForeground(new java.awt.Color(255, 255, 255));

TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null}
    },
    new String [] {
        "transaction_id", "user_id", "payment_id", "amount", "comment"
    }
));



ScrollPaneTablaUsers.setViewportView(TablaUsers);
    }
    
    private void funcionAltas(){
         if(txttransaction_id.getText().equals("")){
         txttransaction_id.setBackground(Color.red);
          txttransaction_id.setText("Campo VACIO");
         txttransaction_id.requestFocus();
     } else if(txtpayment_id.getText().equals("")){
         txtpayment_id.setBackground(Color.red);
         txtpayment_id.setText("Campo VACIO");
         txtpayment_id.requestFocus();
         
     }else if(txtuser_id.getText().equals("")){
         txtuser_id.setBackground(Color.red);
         txtuser_id.setText("Campo VACIO");
         txtuser_id.requestFocus();
     }else if(txtamount.getText().equals("")){
         txtamount.setBackground(Color.red);
         txtamount.setText("Campo VACIO");
         txtamount.requestFocus();
     }else if(txttype.getText().equals("")){
         txttype.setBackground(Color.red);
         txttype.setText("Campo VACIO");
         txttype.requestFocus();
     
     }else if(txtcomment.getText().equals("")){
         txtcomment.setBackground(Color.red);
         txtcomment.setText("Campo VACIO");
         txtcomment.requestFocus();
     
     }
     
     else{
         
          IUserTransactionDAO dao = new UserTransactionDaoImpl();
        int transaction_id = Integer.parseInt(txttransaction_id.getText());
        int payment_id = Integer.parseInt(txtpayment_id.getText());
        int user_id = Integer.parseInt(txtuser_id.getText());
     int amount = Integer.parseInt(txtamount.getText());
     String comment = txtcomment.getText();
     String type = txttype.getText();
    
     UserTransaction ut = new UserTransaction(transaction_id,user_id,
     amount,type,comment,payment_id);
           if(dao.registrar(ut)){
         btnValidar.setVisible(true);
         btnValidar.setText("Registro COMPLETADO");
         actualizarTabla();
         
     }else{
         btnValidar.setVisible(true);
         btnValidar.setText("Registro NO COMPLETADO");
     }
    }
    }
    
    public void funcionBajas(){
        UserTransactionDaoImpl dao = new UserTransactionDaoImpl();
        UserTransaction ut = dao.obtenertransaccion(txttransaction_id.getText());
        if(dao.eliminar(ut)){
            txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        
         txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
        
        
       
        
        btnValidar.setVisible(true);
                 btnValidar.setText("Eliminacion exitosa");
                 actualizarTabla();
        }else{
            btnValidar.setVisible(true);
                 btnValidar.setText("Eliminacion fallida");
                 btnValidar.setBackground(Color.red);
        }
        
    }
    
    private void funcionCambios(){
         if(txttransaction_id.getText().equals("")){
         txttransaction_id.setBackground(Color.red);
          txttransaction_id.setText("Campo VACIO");
         txttransaction_id.requestFocus();
     } else if(txtpayment_id.getText().equals("")){
         txtpayment_id.setBackground(Color.red);
         txtpayment_id.setText("Campo VACIO");
         txtpayment_id.requestFocus();
         
     }else if(txtuser_id.getText().equals("")){
         txtuser_id.setBackground(Color.red);
         txtuser_id.setText("Campo VACIO");
         txtuser_id.requestFocus();
     }else if(txtamount.getText().equals("")){
         txtamount.setBackground(Color.red);
         txtamount.setText("Campo VACIO");
         txtamount.requestFocus();
     }else if(txttype.getText().equals("")){
         txttype.setBackground(Color.red);
         txttype.setText("Campo VACIO");
         txttype.requestFocus();
     }else if(txtcomment.getText().equals("")){
         txtcomment.setBackground(Color.red);
         txtcomment.setText("Campo VACIO");
         txtcomment.requestFocus();
     }else{
         
         IUserTransactionDAO dao = new UserTransactionDaoImpl();
        int transaction_id = Integer.parseInt(txttransaction_id.getText());
        int payment_id = Integer.parseInt(txtpayment_id.getText());
        int user_id = Integer.parseInt(txtuser_id.getText());
     int amount = Integer.parseInt(txtamount.getText());
     String comment = txtcomment.getText();
     String type = txttype.getText();
    
     UserTransaction ut = new UserTransaction(transaction_id,user_id,
     amount,type,comment,payment_id);
           if(dao.registrar(ut)){
         btnValidar.setVisible(true);
         btnValidar.setText("Registro COMPLETADO");
         actualizarTabla();
         
     }else{
         btnValidar.setVisible(true);
         btnValidar.setText("Registro NO COMPLETADO");
     }
    }

        
}
    public void funcionConsultas(){
        UserDaoImpl dao = new UserDaoImpl();
        dao.consultar(armarConsulta(),TablaUsers);
        
    }
    
    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked
        // TODO add your handling code here:
        if(rbAltas1.isSelected()){
           funcionAltas(); 
        }else if(rbBajas.isSelected()){
            funcionBajas();
        }else if(rbCambios.isSelected()){
            funcionCambios();
        }else if(rbConsultas.isSelected()){
            funcionConsultas();
        }
        
     
     
     
   
     
     
    }//GEN-LAST:event_btnagregarMouseClicked

    private void txttransaction_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttransaction_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txttransaction_id.setText("Ingresa Solo Numeros");}
        
        
    }//GEN-LAST:event_txttransaction_idKeyTyped

    private void btnrestablecerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnrestablecerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestablecerKeyPressed

    private void btnrestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrestablecerMouseClicked
        // TODO add your handling code here:
        txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
       
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnrestablecerMouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarMouseClicked

    private void rbBajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbBajasMouseClicked
        // TODO add your handling code here:
        tablaOriginal();
        actualizarTabla();
        btnValidar.setVisible(false);
        btnBuscar.setVisible(true);
        txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
          txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
       
        
        cbtransaction_id.setVisible(false);
        cbtransaction_id1.setVisible(false);
        cbuser_id.setVisible(false);
        cbuser_id1.setVisible(false);
        cbpayment_id.setVisible(false);
        cbpayment_id1.setVisible(false);
        cbpayment_id.setVisible(false);
    
        cbamount.setVisible(false);
        cbamount1.setVisible(false);
      
        cbcomment.setVisible(false);
        
        cbcomment1.setVisible(false);
        
        cbtype.setVisible(false);
        cbtype2.setVisible(false);
        
       
        
        btnVisor.setVisible(false);
        btnagregar.setText("Eliminar");
        
    }//GEN-LAST:event_rbBajasMouseClicked

    private void rbAltas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAltas1MouseClicked
        // TODO add your handling code here:
        tablaOriginal();
        actualizarTabla();
         btnBuscar.setVisible(false);
         btnValidar.setVisible(false);
        txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        
        btnValidar.setVisible(false);
        btnBuscar.setVisible(true);
        txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
          txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
       
        
        cbtransaction_id.setVisible(false);
        cbtransaction_id1.setVisible(false);
        cbuser_id.setVisible(false);
        cbuser_id1.setVisible(false);
        cbpayment_id.setVisible(false);
        cbpayment_id1.setVisible(false);
        cbpayment_id.setVisible(false);
    
        cbamount.setVisible(false);
        cbamount1.setVisible(false);
      
        cbcomment.setVisible(false);
        
        cbcomment1.setVisible(false);
        
        cbtype.setVisible(false);
        cbtype2.setVisible(false);
        
        
        btnVisor.setVisible(false);
        btnagregar.setText("Agregar");
    }//GEN-LAST:event_rbAltas1MouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if(txttransaction_id.getText().equals("")){
            txttransaction_id.setText("Ingrese ID ....");
            txttransaction_id.setBackground(Color.CYAN);
        }
        else{
            UserTransactionDaoImpl dao = new UserTransactionDaoImpl();
            UserTransaction ut = dao.obtenertransaccion(txttransaction_id.getText());
            
            txttransaction_id.setText(String.valueOf(ut.getTransaction_id()));
            txtpayment_id.setText(String.valueOf(ut.getPayment_id()));
            txtuser_id.setText(String.valueOf(ut.getUser_id()));
            txtamount.setText(String.valueOf(ut.getAmount()));
            txttype.setText(String.valueOf(ut.getType()));
            txtcomment.setText(String.valueOf(ut.getComment()));
          
            
  
        }
    }//GEN-LAST:event_btnBuscarMouseClicked
    
    private String armarConsulta(){
       String instruccion ="SELECT ";
       if(cbtransaction_id.isSelected()){
           instruccion+="transaction_id,";
       }
       if(cbuser_id.isSelected()){
           instruccion+="user_id,";
       }
       if(cbpayment_id.isSelected()){
           instruccion+="payment_id,";
       }
       if(cbamount.isSelected()){
           instruccion+="amount,";
       }
       if(cbcomment.isSelected()){
           instruccion+="comment,";
       }
       if(cbtype.isSelected()){
           instruccion+="type,";
       }
       
       
       if (instruccion.endsWith(",")) {
    instruccion = instruccion.substring(0, instruccion.length() - 1) + "";}
    
    String instruccion2 =" FROM CHENTE.USERTRANSACTION WHERE ";
    
    
    if(cbtransaction_id1.isSelected()){
           instruccion2+="AND transaction_id = "+"'"+txttransaction_id.getText()+"'"+" ";
       }
       if(cbpayment_id1.isSelected()){
           instruccion2+="AND payment_id = "+"'"+txtpayment_id.getText()+"'"+" ";
       }
       if(cbuser_id1.isSelected()){
           instruccion2+="AND user_id = "+"'"+txtuser_id.getText()+"'"+" ";
       }
       if(cbamount1.isSelected()){
           instruccion2+="AND amount = "+"'"+txtamount.getText()+"'"+" ";
       }
       if(cbtype2.isSelected()){
           instruccion2+="AND type = "+"'"+txttype.getText()+"'"+" ";
       }
       if(cbcomment1.isSelected()){
           instruccion2+="AND comment = "+"'"+txtcomment.getText()+"'"+" ";
       }
       
       
       
       
        if (instruccion2.endsWith(",")) {
    instruccion2 = instruccion2.substring(0, instruccion2.length() - 1) + "";}
        
        String cadenaRegreso = (instruccion+instruccion2).replaceFirst("AND", "");
        
       

         
         
        
    
     return cadenaRegreso;
    
}
       
       
    
    
    private void rbCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCambiosMouseClicked
        // TODO add your handling code here:
        tablaOriginal();
        actualizarTabla();
        btnValidar.setVisible(false);
        btnBuscar.setVisible(true);
        txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        
        txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
       
        cbtransaction_id.setVisible(false);
        cbtransaction_id1.setVisible(false);
        cbuser_id.setVisible(false);
        cbuser_id1.setVisible(false);
        cbpayment_id.setVisible(false);
        cbpayment_id1.setVisible(false);
        cbpayment_id.setVisible(false);
    
        cbamount.setVisible(false);
        cbamount1.setVisible(false);
      
        cbcomment.setVisible(false);
        
        cbcomment1.setVisible(false);
        
        cbtype.setVisible(false);
        cbtype2.setVisible(false);
        
        btnVisor.setVisible(false);
        btnagregar.setText("Actualizar");
        
    }//GEN-LAST:event_rbCambiosMouseClicked

    private void rbConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbConsultasMouseClicked
        // TODO add your handling code here:
        btnValidar.setVisible(false);
        btnBuscar.setVisible(false);
        btnagregar.setText("Consultar");
         cbtransaction_id.setVisible(true);
        cbtransaction_id1.setVisible(true);
        cbuser_id.setVisible(true);
        cbuser_id1.setVisible(true);
        cbpayment_id.setVisible(true);
        cbpayment_id1.setVisible(true);
        cbpayment_id.setVisible(true);
    
        cbamount.setVisible(true);
        cbamount1.setVisible(true);
      
        cbcomment.setVisible(true);
        
        cbcomment1.setVisible(true);
        
        
        
        
          txttransaction_id.setText("");
        txttransaction_id.setBackground(Color.GRAY);
        txtpayment_id.setText("");
        txtpayment_id.setBackground(Color.GRAY);
        txtuser_id.setText("");
        txtuser_id.setBackground(Color.GRAY);
        txtamount.setText("");
        txtamount.setBackground(Color.GRAY);
        txttype.setText("");
        txttype.setBackground(Color.GRAY);
        txtcomment.setText("");
        txtcomment.setBackground(Color.GRAY);
        
        cbtype.setVisible(true);
        cbtype2.setVisible(true);
        
        btnVisor.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_rbConsultasMouseClicked

    private void btnVisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisorMouseClicked
        // TODO add your handling code here:
        System.out.println(armarConsulta());
    }//GEN-LAST:event_btnVisorMouseClicked

    private void cbuser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuser_idActionPerformed

    private void cbuser_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuser_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuser_id1ActionPerformed

    private void txtcommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcommentActionPerformed

    private void txtuser_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txtuser_id.setText("Ingresa Solo Numeros");}
    }//GEN-LAST:event_txtuser_idKeyTyped

    private void txtpayment_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayment_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txtpayment_id.setText("Ingresa Solo Numeros");}
    }//GEN-LAST:event_txtpayment_idKeyTyped

    private void txtamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();


                if(((c < '0') || (c > '9'))
                        && (c != KeyEvent.VK_BACK_SPACE)
                        ) {
                    getToolkit().beep();

                    evt.consume();

                    txtamount.setText("Ingresa Solo Numeros");}
    }//GEN-LAST:event_txtamountKeyTyped

    private void cbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtypeActionPerformed
     
    
    public void actualizarTabla(){

        final String TABLA_USERS = "usertransaction";//esto pede ser parametro

        String driver = "com.ibm.db2.jcc.DB2Driver";
        String url = "jdbc:db2://localhost:50000/DB_SPS";
        String user = "chester";
        String password = "chesterf51997";
        String query = "SELECT * FROM CHENTE." + TABLA_USERS;

        ResultSetTableModel modelo = null;
        try {
            modelo = new ResultSetTableModel(driver, url, user, password, query);
        } catch (SQLException e1) {
            e1.printStackTrace();
        } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
        }

        TablaUsers.setModel(modelo);

    }
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsersTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsersTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsersTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsersTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUsersTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneTablaUsers;
    private javax.swing.JTable TablaUsers;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVisor;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnrestablecer;
    private javax.swing.JCheckBox cbamount;
    private javax.swing.JCheckBox cbamount1;
    private javax.swing.JCheckBox cbcomment;
    private javax.swing.JCheckBox cbcomment1;
    private javax.swing.JCheckBox cbpayment_id;
    private javax.swing.JCheckBox cbpayment_id1;
    private javax.swing.JCheckBox cbtransaction_id;
    private javax.swing.JCheckBox cbtransaction_id1;
    private javax.swing.JCheckBox cbtype;
    private javax.swing.JCheckBox cbtype2;
    private javax.swing.JCheckBox cbuser_id;
    private javax.swing.JCheckBox cbuser_id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jplIngreso;
    private javax.swing.JRadioButton rbAltas1;
    private javax.swing.JRadioButton rbBajas;
    private javax.swing.JRadioButton rbCambios;
    private javax.swing.JRadioButton rbConsultas;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcomment;
    private javax.swing.JTextField txtpayment_id;
    private javax.swing.JTextField txttransaction_id;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtuser_id;
    // End of variables declaration//GEN-END:variables
}
