/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import AppPackage.AnimationClass;
import Graficas.EGraficas;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.IUserDAO;
import modelo.IUserTransactionDAO;
import modelo.Reportes;
import modelo.User;
import modelo.UserDaoImpl;
import modelo.UserTransaction;
import modelo.UserTransactionDaoImpl;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import vista.ResultSetTableModel;

/**
 *
 * @author Chente
 */
public class FrameGraficas extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrameGraficas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplIngreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbCircular = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        rb3D = new javax.swing.JRadioButton();
        rb2D = new javax.swing.JRadioButton();
        rbBarras = new javax.swing.JRadioButton();
        cbConsultaSeleccionada = new javax.swing.JComboBox();
        btnEjecutar = new javax.swing.JButton();
        Graficar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbcomment = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGraficas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplIngreso.setBackground(new java.awt.Color(204, 204, 0));
        jplIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplIngreso.setForeground(new java.awt.Color(204, 204, 0));
        jplIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafico-de-estadisticas-de-futbol.png"))); // NOI18N
        jplIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 110));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Opciones");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jplIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rbCircular.setBackground(new java.awt.Color(51, 51, 51));
        rbCircular.setForeground(new java.awt.Color(255, 255, 255));
        rbCircular.setText("CIRCULAR");
        rbCircular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCircularMouseClicked(evt);
            }
        });
        rbCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCircularActionPerformed(evt);
            }
        });
        jplIngreso.add(rbCircular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));
        jplIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 10));
        jplIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 270, 10));
        jplIngreso.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, 10));

        rb3D.setBackground(new java.awt.Color(51, 51, 51));
        rb3D.setForeground(new java.awt.Color(255, 255, 255));
        rb3D.setText("3D");
        rb3D.setSelected(true);
        rb3D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb3DMouseClicked(evt);
            }
        });
        rb3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3DActionPerformed(evt);
            }
        });
        jplIngreso.add(rb3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        rb2D.setBackground(new java.awt.Color(51, 51, 51));
        rb2D.setForeground(new java.awt.Color(255, 255, 255));
        rb2D.setText("2D");
        rb2D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb2DMouseClicked(evt);
            }
        });
        rb2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2DActionPerformed(evt);
            }
        });
        jplIngreso.add(rb2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        rbBarras.setBackground(new java.awt.Color(51, 51, 51));
        rbBarras.setForeground(new java.awt.Color(255, 255, 255));
        rbBarras.setText("BARRAS");
        rbBarras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbBarrasMouseClicked(evt);
            }
        });
        rbBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBarrasActionPerformed(evt);
            }
        });
        jplIngreso.add(rbBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        cbConsultaSeleccionada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoger consulta", "Agrupar por performance", "Agrupar por tipo de apuesta" }));
        cbConsultaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultaSeleccionadaActionPerformed(evt);
            }
        });
        jplIngreso.add(cbConsultaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        jplIngreso.add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Graficar.setText("Graficar");
        Graficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GraficarMouseClicked(evt);
            }
        });
        Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarActionPerformed(evt);
            }
        });
        jplIngreso.add(Graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        getContentPane().add(jplIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 0));

        cbcomment.setText("comment");
        cbcomment.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(cbcomment)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbcomment)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaGraficas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaGraficas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 90));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 520, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCircularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCircularActionPerformed

    private void rb3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3DActionPerformed

    private void rb2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2DActionPerformed

    private void rbBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBarrasActionPerformed

    
    
    
    
    private void rb2DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2DMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_rb2DMouseClicked

    private void rb3DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb3DMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rb3DMouseClicked
    
  
       
       
    
    
    private void rbBarrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbBarrasMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbBarrasMouseClicked

    private void rbCircularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCircularMouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_rbCircularMouseClicked

    private void cbConsultaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultaSeleccionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConsultaSeleccionadaActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
         DefaultTableModel miModelo;
        EGraficas miGrafica = new EGraficas();
        int op = cbConsultaSeleccionada.getSelectedIndex();
        switch(op){
            case 1:
                miModelo = miGrafica.agruparPerformance();
                TablaGraficas.setModel(miModelo);
                break;
            case 2:
                miModelo = miGrafica.agruparTipoApuesta();
                TablaGraficas.setModel(miModelo);
                break;
            
            default: JOptionPane.showMessageDialog(rootPane, "Sigue Asi!!!!");
        }   
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void GraficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraficarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GraficarMouseClicked

    private void GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarActionPerformed
        // TODO add your handling code here:
        if(rb3D.isSelected() && rbBarras.isSelected()){
            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            
            for(int i = 0; i < TablaGraficas.getRowCount(); i++){
                dtsc.setValue(Integer.parseInt(TablaGraficas.getValueAt(i, 0).toString()), TablaGraficas.getValueAt(i, 2).toString(), TablaGraficas.getValueAt(i, 2).toString());
            }
            JFreeChart ch = ChartFactory.createBarChart3D("Grafica de barras 3D", "Cantidad", "Genero", dtsc,PlotOrientation.HORIZONTAL, true, true, false);
            ChartPanel cp = new ChartPanel(ch);
            
            jPanel3.add(cp);
          
            
            
        }
        if(rb2D.isSelected() && rbBarras.isSelected()){
            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            
            for(int i = 0; i < TablaGraficas.getRowCount(); i++){
                dtsc.setValue(Integer.parseInt(TablaGraficas.getValueAt(i, 0).toString()), TablaGraficas.getValueAt(i, 1).toString(), TablaGraficas.getValueAt(i, 2).toString());
            }
            JFreeChart ch = ChartFactory.createBarChart("Grafica de barras 3D", "Cantidad", "Genero", dtsc,PlotOrientation.HORIZONTAL, true, true, false);
            ChartPanel cp = new ChartPanel(ch);
           
           
            
        }        
        
        if(rb3D.isSelected() && rbCircular.isSelected()){
            DefaultPieDataset dtsc = new DefaultPieDataset();
            
            for(int i = 0; i < TablaGraficas.getRowCount(); i++){
                dtsc.setValue(TablaGraficas.getValueAt(i, 0).toString(), Integer.parseInt(TablaGraficas.getValueAt(i, 1).toString()));
            }
            JFreeChart ch = ChartFactory.createPieChart3D("Grafica de barras 3D", dtsc,true, true, false);
            ChartPanel cp = new ChartPanel(ch);
          
            
        }        
        if(rb2D.isSelected() && rbCircular.isSelected()){
            DefaultPieDataset dtsc = new DefaultPieDataset();
            
            for(int i = 0; i < TablaGraficas.getRowCount(); i++){
                dtsc.setValue(TablaGraficas.getValueAt(i, 0).toString(), Integer.parseInt(TablaGraficas.getValueAt(i, 1).toString()));
            }
            JFreeChart ch = ChartFactory.createPieChart("Grafica de barras 3D", dtsc,true, true, false);
            ChartPanel cp = new ChartPanel(ch);
            
        }
            
    }//GEN-LAST:event_GraficarActionPerformed
     
         
         
    

    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGraficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Graficar;
    private javax.swing.JTable TablaGraficas;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JComboBox cbConsultaSeleccionada;
    private javax.swing.JCheckBox cbcomment;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel jplIngreso;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JRadioButton rbBarras;
    private javax.swing.JRadioButton rbCircular;
    // End of variables declaration//GEN-END:variables
}
